url: "https://tanakamawere.co.zw" # the base hostname & protocol for your site, e.g. http://example.com
description: "Incompetent C# Programmer and Keyboardist + Bassist from Harare. Currently an unfortunate medical student at UZ and pretends to exercise at times."

baseurl: "/" # the subpath of your site, e.g. /blog
title: "Tanaka Mawere" # the name of your site, e.g. ACME Corp.
